### ISSUE TITLE
AttributeError: 'XceptionWrapper_public' object has no attribute 'preprocess_single_img'

### ISSUE THREAD

**Issue by Lilianfang** [gyhandy/Visual-Reasoning-eXplanation#1]
Hi, When I run the discover_concept.py, thr wrong happend. Help!

**Comment by Infernaught** [comment]
I'm also running into this error. Have you found a workaround for this yet?

**Comment by avaxiao** [comment]
Sorry for the error, and we have fixed the bug. Please try again, thanks!
