### ISSUE TITLE
Some issues about functions of the Xception model.

### ISSUE THREAD

**Issue by ddghjikle** [gyhandy/Visual-Reasoning-eXplanation#2]
Hi, thank you very much for your hard work and kindness sharing. In the provided codes, it seems that the Xception model dose not have the follow function: preprocess_single_img (called in ace.py, line 210), which is important for using self._return_gradcam_superpixels (ace.py, line 185). Could you give us some assistance to handle this issue? Again, thank you very much for your help and hard work.

**Comment by avaxiao** [comment]
Thank you for reaching out, and we have fixed this bug. Please check again, thanks!
