### ISSUE TITLE
I got an error when I ran ‘discover_concept.py’

### ISSUE THREAD

**Issue by PeterZhang97** [gyhandy/Visual-Reasoning-eXplanation#3]
When I run to ‘calculate Calculating CAVs and TCAV scores of ambulance...’，
I got this error：ValueError: Input 0 of layer block1_conv1 is incompatible with the layer: expected ndim=4, found ndim=3. Full shape received: [224, 224, 3]

Hope you can help me！
Thanks！

**Comment by gyhandy** [comment]
您好，我已经收到您的来信，祝好

**Comment by gyhandy** [comment]
which line will cause the error？Could you provide more information? Thanks!

**Comment by gyhandy** [comment]
Please try [299, 299, 3] or [1, 299, 299, 3]  if you use Xception

**Comment by PeterZhang97** [comment]
> Please try [299, 299, 3] or [1, 299, 299, 3] if you use Xception
Change it to [1, 299, 299, 3] and there is no error. Thank you!

**Comment by gyhandy** [comment]
您好，我已经收到您的来信，祝好
