### ISSUE TITLE
Questions about Xception_XAI_graph_training.dataset

### ISSUE THREAD

**Issue by LiuuCSDN** [gyhandy/Visual-Reasoning-eXplanation#4]
hello,I want to know where can i find "result/vec2graph/Xception_XAI_graph_training.dataset",i downloaded "source","result"folder,but i can't find it.I look forward to your reply.

**Comment by gyhandy** [comment]
您好，我已经收到您的来信，祝好

**Comment by LiuuCSDN** [comment]
Is "Xception_XAI_graph_training.dataset“ made up of xxxxxx_XAI.npy？

**Comment by gyhandy** [comment]
Xception_XAI_graph_training.dataset is the data to train the final graph neural network. It can be generated by "VR_training_XAI.py" with the class VR_graph.

**Comment by LiuuCSDN** [comment]
Thanks a lot!
